version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: moodle-memcached

    redis:
      image: redis:alpine
      container_name: moodle-redis

    mysql:
      image: mysql:5.7
      container_name: moodle-mysql
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=moodle
        - MYSQL_USER=moodle
        - MYSQL_PASSWORD=moodle

    webserver:
      build:
        context: .
        dockerfile: phpdocker/nginx/Dockerfile
      container_name: moodle-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/common.include.conf:/etc/nginx/common.include.conf
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./phpdocker/nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
      ports:
       - "8080:8080"
       - "443:443"
      links:
       - php-fpm

    php-fpm:
      build:
        context: .
        dockerfile: phpdocker/php-fpm/Dockerfile
      container_name: moodle-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
        - ./phpdocker/php-fpm/clamd.conf:/etc/clamav/clamd.conf
        - ./phpdocker/php-fpm/freshclam.conf:/etc/clamav/freshclam.conf
      links:
        - memcached
        - mysql
        - redis
